### ISSUE TITLE
Convert from React Context to Redux

### ISSUE THREAD

**Issue by jacoblurie29** [jacoblurie29/Personile#15]
Implemented the react context first to manage the state of the app, then use that to convert to Redux with Redux toolkit. Take notes on Redux along the way

**Comment by Weave-Trix** [comment]
Hi, do you need help on this?

**Comment by jacoblurie29** [comment]
7/4 - Added react context for app

**Comment by jacoblurie29** [comment]
Redux implemented and react context removed completely
